// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mopvfocrrymeixagwmmh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1vcHZmb2NycnltZWl4YWd3bW1oIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI0NDM1NjcsImV4cCI6MjA1ODAxOTU2N30.3_NQ4FdQ35zwqvcZDKsoYBlxSs34Vz1Hr3j-8i6p7SQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);